name: buildcheck

on:
  pull_request:
  push:
  schedule:
    - cron: 0 10 21 * *

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        composer:
          - ""
          - "--prefer-lowest"

    steps:
      - uses: actions/checkout@v1

      - name: Create Docker Container
        run: |
          docker build . -t ci-image --build-arg PHP_VERSION=${{ matrix.php }}
          docker run --interactive --detach --volume ${{ github.workspace }}:/app --name ci ci-image

      - name: Install Dependencies
        run: docker exec ci composer update --no-interaction --no-ansi --prefer-dist ${{ matrix.composer }}

      - name: PHPUnit
        run: docker exec ci vendor/bin/phpunit

      - name: Coding Standards
        run: docker exec ci vendor/bin/phpcs

      - name: Check Dependencies
        run: docker exec ci vendor/bin/composer-require-checker

      - name: Composer Validate
        run: docker exec ci composer validate --strict

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: Install Dependencies
        run: composer update --no-interaction --no-ansi --prefer-dist

      - name: PHPUnit
        run: vendor/bin/phpunit
